### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by myfirstgithubaccHk** [ALKR-HACKHECKZ/alkrinsta#8]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by xxxxx-ux** [comment]
Same problem

**Comment by reahan007** [comment]
$ pkg update
$ pkg install python
$ pkg install python.pip
$ pip install requests
$ import requests
**_### now u enter again_** 
$ python3 alkrinsta.py
### **Error resolve**

**Comment by Sonya1122** [comment]
~/alkrinsta $ ls
README.md     cupp.cfg  pass.txt   test_cupp.py
alkrinsta.py  cupp.py   proxy.txt
~/alkrinsta $ python3 alkrinsta.py
Please enter a username: aditya_ukirade
[*] 11140 Passwords loads successfully            [*] Do you want to use proxy (y/n): n
[*] Please add delay between the bruteforce action (in seconds): 2                                  
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 146, in <module>
    sess = instabrute.Login(password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 110, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})                                                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'csrftoken'                             ~/alkrinsta $
